version: '3.8'

services:
  web:
    image: 3d_human_body_shape:1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./.tmp:/app/.tmp
      - /usr/local/cuda:/usr/local/cuda
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDACXX=/usr/local/cuda/bin/nvcc
      # FLASK_ENV: development

