version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src  # Mount your src directory to /app/src in the container
    environment:
      FLASK_ENV: development  # Set Flask environment to development
