version: '3.8'

services:
  web:
    image: 3d_human_body_shape:1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./.tmp:/app/.tmp
    # environment:
      # FLASK_ENV: development
